services:
  application:
    container_name: utilcord
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    networks:
      - stack

networks:
  stack:
    name: stack
    driver: bridge