services:
  application:
    container_name: utilcord
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DISCORD_JDA_KEY = ${DISCORD_JDA_KEY}
      - GOOGLE_SCRIPT_TRANSLATOR_DEPLOYMENT_ID = ${GOOGLE_SCRIPT_TRANSLATOR_DEPLOYMENT_ID}
      - CURRENCY_TRANSLATOR_API_KEY = ${CURRENCY_TRANSLATOR_API_KEY}
    networks:
      - stack

networks:
  stack:
    name: stack
    driver: bridge