name: Maven Build and Test

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch
  pull_request:
    branches: [ main ]  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use a Linux-based runner with Maven

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven  # Cache Maven dependencies for faster builds

      - name: Build and test with Maven
        run: mvn clean package

      - name: Upload packaged artifact
        uses: actions/upload-artifact@v3
        with:
          name: bot.zip
          path: target/bot.zip
